<?php

namespace WEB\LoveLetterBundle\Repository;

/**
 * mainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class mainRepository extends \Doctrine\ORM\EntityRepository
{
}
