<?php

namespace WEB\LoveLetterBundle\Repository;

/**
 * mancheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class mancheRepository extends \Doctrine\ORM\EntityRepository
{
}
