<?php

namespace WEB\LoveLetterBundle\Repository;

/**
 * piocheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class piocheRepository extends \Doctrine\ORM\EntityRepository
{
}
