<?php

namespace WEB\LoveLetterBundle\Repository;

/**
 * plateauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class plateauRepository extends \Doctrine\ORM\EntityRepository
{
}
