oc_platform_home:
    path:      /
    defaults:
        _controller: WEBLoveLetterBundle:Advert:index
        page:        1
    requirements:
        page: \d*

oc_platform_jouer:
    path:      /advert/jouer/{id}
    defaults:
        _controller: WEBLoveLetterBundle:Advert:jouer
    requirements:
        id: \d+

oc_platform_jouer2:
    path:      /advert/jouer2/{id}
    defaults:
        _controller: WEBLoveLetterBundle:Advert:jouer2
    requirements:
        id: \d+

oc_platform_piocher:
    path:      /advert/piocher/{enemy_check}
    defaults:
        _controller: WEBLoveLetterBundle:Advert:piocher
    requirements:
        id: \d+

oc_platform_poser:
    path:     /advert/poser/{idcarte}/{carte}/{typeCarte}
    defaults:
        _controller: WEBLoveLetterBundle:Advert:poser
    requirements:
        id: \d+

oc_platform_gestion:
    path:      /advert/gestion/{nb_joueurs}/{finManche}
    defaults:
        _controller: WEBLoveLetterBundle:Advert:gestion
    requirements:
        id: \d+

oc_platform_adversaire2:
    path:      /advert/adversaire2
    defaults:
        _controller: WEBLoveLetterBundle:Refresh:adversaire2
    requirements:
        id: \d+

oc_platform_refresh:
    path:      /advert/refresh
    defaults:
        _controller: WEBLoveLetterBundle:Refresh:refresh
    requirements:
        id: \d+

oc_platform_refreshMain:
    path:      /advert/refreshMain
    defaults:
        _controller: WEBLoveLetterBundle:Refresh:refreshMain
    requirements:
        id: \d+

oc_platform_menu:
    path:      /advert/menu/{id}
    defaults:
        _controller: WEBLoveLetterBundle:Advert:menu
    requirements:
        id: \d+

oc_platform_prince:
    path:      /advert/prince/{nomUtilisateur}
    defaults:
        _controller: WEBLoveLetterBundle:Effet:prince
    requirements:
        id: \d+

oc_platform_baron:
    path:      /advert/baron
    defaults:
        _controller: WEBLoveLetterBundle:Effet:baron
    requirements:
        id: \d+

oc_platform_guard:
    path:      /advert/guard/{carteD}
    defaults:
        _controller: WEBLoveLetterBundle:Effet:guard
    requirements:
        id: \d+

oc_platform_king:
    path:      /advert/king
    defaults:
        _controller: WEBLoveLetterBundle:Effet:king
    requirements:
        id: \d+

oc_platform_pretre:
    path:      /advert/pretre/{nomEnemy}/{checkvisible}
    defaults:
        _controller: WEBLoveLetterBundle:Effet:pretre
    requirements:
        id: \d+