oc_platform_home:
    path:      /
    defaults:
        _controller: WEBLoveLetterBundle:Advert:index
        page:        1
    requirements:
        page: \d*

oc_platform_jouer:
    path:      /advert/jouer/{id}
    defaults:
        _controller: WEBLoveLetterBundle:Advert:jouer
    requirements:
        id: \d+

oc_platform_jouer2:
    path:      /advert/jouer2/{id}
    defaults:
        _controller: WEBLoveLetterBundle:Advert:jouer2
    requirements:
        id: \d+

oc_platform_piocher:
    path:      /advert/piocher
    defaults:
        _controller: WEBLoveLetterBundle:Advert:piocher
    requirements:
        id: \d+

oc_platform_poser:
    path:      /advert/poser/{idcarte}/{carte}
    defaults:
        _controller: WEBLoveLetterBundle:Advert:poser
    requirements:
        id: \d+

oc_platform_gestion:
    path:      /advert/gestion/{nb_joueurs}
    defaults:
        _controller: WEBLoveLetterBundle:Advert:gestion
    requirements:
        id: \d+

oc_platform_adversaire2:
    path:      /advert/adversaire2
    defaults:
        _controller: WEBLoveLetterBundle:Advert:adversaire2
    requirements:
        id: \d+

oc_platform_refresh:
    path:      /advert/refresh
    defaults:
        _controller: WEBLoveLetterBundle:Refresh:refresh
    requirements:
        id: \d+

oc_platform_menu:
    path:      /advert/menu/{id}
    defaults:
        _controller: WEBLoveLetterBundle:Advert:menu
    requirements:
        id: \d+

oc_platform_guard:
    path:      /advert/guard/{carteA}/{carteD}
    defaults:
        _controller: WEBLoveLetterBundle:Effet:guard
    requirements:
        id: \d+